name = 'Air'
license = 'MIT'
licenselink = 'https://raw.githubusercontent.com/fducat18/hugo-air/refs/heads/main/LICENSE'
description = 'Hugo Air Theme'
version = 'v0.1.5'
screenshot = '/images/screenshot.jpg/'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/fducat18/hugo-air'

# Demo of the theme
demosite = 'https://fducat18.github.io/hugo-air-demo'

# Taxonomy terms
tags = ['gallery', 'blog', 'company', 'website', 'portfolio']
features = ['responsive', 'images gallery', 'page bundle gallery', 'masonry image gallery', 'instagram image gallery', 'google maps', 'bootstrap', 'shortcodes']
min_version = '0.147.7'

# If the theme has a single author
[author]
  name = 'fducat18'
  homepage = 'https://github.com/fducat18/hugo-air'
